// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Service {
    #[prost(string, tag="1")]
    pub schema: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub dbt_config: ::core::option::Option<DbtConfig>,
    #[prost(bool, tag="3")]
    pub wire_protocol_access: bool,
    #[prost(message, optional, tag="4")]
    pub hasura_frontend: ::core::option::Option<HasuraConfig>,
    #[prost(message, optional, tag="5")]
    pub postgraphile_frontend: ::core::option::Option<PostgraphileConfig>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbtConfig {
    #[prost(bytes="vec", tag="1")]
    pub files: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HasuraConfig {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PostgraphileConfig {
}
// @@protoc_insertion_point(module)
