// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilteredAccounts {
    #[prost(message, repeated, tag="1")]
    pub accounts: ::prost::alloc::vec::Vec<::substreams_solana::pb::sf::solana::r#type::v1::Account>,
}
// @@protoc_insertion_point(module)
