

pub const SOLANA_PROGRAM_ACCOUNT:&str = "11111111111111111111111111111111";
pub const SOLANA_TOKEN_PROGRAM: &str = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
pub const HONEY_CONTRACT_ADDRESS: &str = "4vMsoUT2BWatFweudnQM1xedRLfJgJ7hswhcpz4xgBTy";

pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_LIB_CREATE_ACCOUNT: u8 = 232; // 0xe8
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_LIB_BURN: u8 = 193; // 0xc1


// Program
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM: &str =  "BNH1dUp3ExFbgo3YctSqQbJXRFn3ffkwbcmSas8azfaW";

 pub const HONEY_TOKEN_INSTRUCTION_PAY_TO: u8 = 151; // 0x97
pub const HONEY_TOKEN_INSTRUCTION_CREATE_PAYMENT_INVOICE: u8 = 46; // 0x2e
pub const HONEY_TOKEN_INSTRUCTION_INITIALIZE_DEFAULT_PERIOD: u8 = 125; // 0x7d
pub const HONEY_TOKEN_INSTRUCTION_INITIALIZE_PAYMENT_PERIOD: u8 = 248; // 0xf8
pub const HONEY_TOKEN_INSTRUCTION_UPDATE_MAP_PROGRESS: u8 = 215; // 0xd7
pub const HONEY_TOKEN_INSTRUCTION_CREATE_IMAGERY_QA_INVOICE: u8 = 182; // b6
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_PAY_IMAGERY_QA_INVOICE: u8 = 187; // 0xbb
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_PAY_OPERATIOANL_REWARD: u8 = 241; // 0xf1
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_PAY_AND_FORWARD_REWARD_AC: u8 = 172; // 0xac
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_PAY_AND_FORWARD_REWARD_SPLIT_E9: u8 =  233; // 0xe9
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_REMOVE_INVOICE: u8 = 11; // 0x0b
pub const HONEY_TOKEN_INSTRUCTION_PAY_MAP_COMSUMPTION_REWARD: u8 = 179; // 0xb3
pub const HONEY_TOKEN_INSTRUCTION_PROGRAM_PAY_REWARD: u8 = 107; // 0x6b
pub const HONEY_TOKEN_INSTRUCTION_PAY_AND_FORWARD_CONSUMPTION_REWARD: u8 = 8; // 0x08
pub const HONEY_TOKEN_INSTRUCTION_PAY_CONSUMPTION_REWARD: u8 = 144; //0x90
pub const HONEY_TOKEN_INSTRUCTION_PAY_BURST_REWARD: u8 = 129; //0x81
pub const HONEY_TOKEN_INSTRUCTION_PAY_AND_FORWARD_BURST_REWARD: u8 = 120; //0x78









pub const HONEY_TOKEN_INSTRUCTION_LIB: &str  = "EEjwuvCMVYjgHUeX1BM9qmUog59Pft88c3jbt2ATwcJw";

pub const HONEY_TOKEN_LIB_INITIALIZE_GLOBAL_STATE: u8 = 232;// 0xe8
pub const HONEY_LIB_MAP_CREATE: u8 = 193;// 0xC1
pub const HONEY_LIB_MINT_TO: u8 = 241; // 0xf1
pub const HONEY_LIB_BURN_AND_ADD_ADDITIONAL_HONEY_SUPPLY: u8 = 157; // 0x9d
pub const HONEY_LIB_BURN: u8 = 116; // 0x74

pub const HONEY_LIB_REINITIALIZE_GLOBAL_STATE: u8 = 155; //0x9b
pub const HONEY_LIB_INITIALIZE_CONSUMPTION_REWARD_META: u8 = 201; //0xc9
pub const HONEY_LIB_MINT_TO_6C: u8 = 108; //0x6c



// pub const HONEY_LIB_TOKEN_SPLITTING_INSTRUCTION_BYTE: u8 = 172; // 0xac
// // pub const HONEY_LIB_NO_TOKEN_SPLITTING_INSTRUCTION_BYTE: u8 = 179; // 0xb3
// // pub const HONEY_LIB_REGULAR_DRIVER_INSTRUCTION_BYTE: u8 = 151; // 0x97
// pub const HONEY_LIB_BURN_MAP_CREDIT: u8 = 226; // 0xe2
// pub const HONEY_LIB_UPDATE_CREDIT_TO_HONEY_RATE: u8 = 182; // 0xb6
// pub const HONEY_LIB_PAY_AND_FORWARD_REWARD: u8 = 233; // 0xe9
//


pub const HONEY_TOKEN_DECIMALS: u8 = 9;
